title: Maximilian Dale
description: Sophomore @ UM CP. Double Majoring in Computer Science and German. Interested in Mechanics, Logistics, Autonomous Vehicles and Big Data.
google_analytics: UA-73557121-1
show_downloads: false
