title: Maximilian Dale
description: Freshman @ UM CP. Double Majoring in Computer Science and German. Interested in Mechanics, Logistics, Autonomous Vehicles and Big Data.
google_analytics: UA-73557121-1
show_downloads: true
theme: jekyll-theme-midnight

gems:
  - jekyll-mentions
